### ISSUE TITLE
Custom http status after function invocation

### ISSUE THREAD

**Issue by xemul** [apache/openwhisk-runtime-go#102]
Hello,

I'm trying to write a web action that can return back different http status codes, but docs say nothing about it. I looked at the code and found that the launcher.go just forwards the returned map back to executor and the executor itself doesn't set any status into ResponceWriter (thus defauling it to StatusOK?).

If someone would want to patch the launcher/executor to allow actions return custom status, what would be the best way to do it?

**Comment by rabbah** [comment]
As with all `webactions` you can set the statusCode property on the response.

```
package main

func Main(args map[string]interface{}) map[string]interface{} {
	name, ok := args["name"].(string)
	if !ok {
		name = "stranger"
	}
	msg := make(map[string]interface{})
	msg["body"] = "Hello, " + name + "!"
	msg["statusCode"] = 201
	return msg
}
```

See docs here https://github.com/apache/openwhisk/blob/master/docs/webactions.md#handling-http-requests-with-actions.

**Comment by rabbah** [comment]
In other words, @xemul do not need to patch the launcher or modify the runtime at all. The function itself can dictate the headers, status code and body of the response.

**Comment by xemul** [comment]
Thanks! I should have read the docs more carefully.
