### ISSUE TITLE
Remove redundant Unmarshal in `gobuild.py.launcher.go`

### ISSUE THREAD

**Issue by matthewrankin** [apache/openwhisk-runtime-go#89]
Below are lines 71–91 of [`common/gobuild.py.launcher.go`][1]. Line 83 appears to be redundant and unnecessary, as it is the same as line 73, which has already unmarshalled the data.

https://github.com/apache/incubator-openwhisk-runtime-go/blob/1cbb96383502ca6df45058d966927c0796c31fbd/common/gobuild.py.launcher.go#L83

https://github.com/apache/incubator-openwhisk-runtime-go/blob/1cbb96383502ca6df45058d966927c0796c31fbd/common/gobuild.py.launcher.go#L73

```go
		// parse one line
		var input map[string]interface{}
		err = json.Unmarshal(inbuf, &input)  // Line 73
		if err != nil {
			log.Println(err.Error())
			fmt.Fprintf(out, "{ error: %q}\n", err.Error())
			continue
		}
		if debug {
			log.Printf("%v\n", input)
		}
		// set environment variables
		err = json.Unmarshal(inbuf, &input)  // Line 83: Appears to be redundant.
		for k, v := range input {
			if k == "value" {
				continue
			}
			if s, ok := v.(string); ok {
				os.Setenv("__OW_"+strings.ToUpper(k), s)
			}
		}
```

[1]: https://github.com/apache/incubator-openwhisk-runtime-go/blob/master/common/gobuild.py.launcher.go

**Comment by matthewrankin** [comment]
Any thoughts or comments?

**Comment by rabbah** [comment]
@sciabarra ??

**Comment by rabbah** [comment]
it does look unnecessary to me @matthewrankin.

**Comment by sciabarracom** [comment]
I think you are right, it was a mistake I did when i rewrote it to include the environment variables. If you sent a PR I test and approve it

**Comment by sciabarracom** [comment]
should be fixed
